services:
  spring-1:
    container_name: ggumtle-spring-1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${GAME_SERVER_PORT}:${GAME_SERVER_PORT}
      - ${METRIC_SERVER_PORT}:${METRIC_SERVER_PORT}
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}

  spring-2:
    container_name: ggumtle-spring-2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${GAME_SERVER_PORT_2}:${GAME_SERVER_PORT}
      - ${METRIC_SERVER_PORT_2}:${METRIC_SERVER_PORT}
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}

  spring-3:
    container_name: ggumtle-spring-3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${GAME_SERVER_PORT_3}:${GAME_SERVER_PORT}
      - ${METRIC_SERVER_PORT_3}:${METRIC_SERVER_PORT}
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}

  mysql:
    image: mysql:8.0
    container_name: ggumtle-mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    volumes:
      - ./db/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
