namespace Networks.Packets
{
    public enum PacketType : short
    {
        // Send
        VerifyToken = 1,
        RoomJoin = 10,
        SceneChange = 30,
        PlayerMove = 40,
        ChestOpen = 50,
        ChestClose = 52,
        GetItem = 54,
        PutItem = 56,
        DiggingStart = 100,
        DiggingQuit = 102,
        JellyStart = 110,
        JellyQuit = 112,
        JellyCount = 121,
        GgumtleJellyEaten = 122,
        MongdungAttack = 60,
        MonggingRevivalStart = 62,
        MonggingRevivalStop = 65,
        MongdungSkill = 67,
        MonggingItemUse = 69,
        MonggingFieldItemUse = 71,
        ExitAttempt = 140,
        
        // Receive
        VerifyTokenResponse = 2,
        RoomJoinResponse = 11,
        SceneChangeResponse = 31,
        InitializeMapResponse = 20,
        InitializePlayerResponse = 21,
        GameStart = 35,
        PlayerMoveResponse = 41,
        ChestOpenResponse = 51,
        ChestCloseResponse = 53,
        GetItemResponse = 55,
        PutItemResponse = 57,
        DiggingStartResponse = 101,
        DiggingQuitResponse = 103,
        JellyStartResponse = 111,
        JellyQuitResponse = 113,
        JellyForceQuitResponse = 114,
        MongdungAttackResponse = 61,
        MonggingRevivalStartResponse = 63,
        MonggingRevivalComplete = 64,
        MonggingRevivalStopResponse = 66,
        MongdungSkillResponse = 68,
        MonggingItemUseResponse = 70,
        MonggingFieldItemUseResponse = 72,
        MonggingStateBroadcast = 42,
        GgumtleSpawn = 43,
        GgumtleState = 120,
        ExitOpen = 130,
        ExitAttemptResponse = 141,
        GameEnd = 200,
    }
}