spring:
  application:
    name: ggumtle

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=${MYSQL_USE_SSL}&serverTimezone=${TIMEZONE}&characterEncoding=${ENCODING}&allowPublicKeyRetrieval=${MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: update

game-server:
    port: ${GAME_SERVER_PORT}
    max-players-per-room: 6
    tick-rate: 30
    id: 1
metric-server:
  port: ${METRIC_SERVER_PORT}

jwt:
  access:
    secret: ${ACCESS_SECRET}

logging:
  level:
    com.ggumtle: TRACE