spring:
  application:
    name: ggumtle

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  access:
    expire: ${ACCESS_EXPIRE}
    secret: ${ACCESS_SECRET}
    header: ${ACCESS_NAME}


logging:
  level:
    com.ggumtle: TRACE